#!/usr/bin/env ruby
=begin
 
             Tone Software Corporation BSD License ("License")
  
                        Acceptance Testing Framework
  
  Please read this License carefully before downloading this software. By
  downloading or using this software, you are agreeing to be bound by the
  terms of this License. If you do not or cannot agree to the terms of
  this License, please do not download or use the software.
  
  Provides facility for creating custom test suites for
  acceptance/regression testing. The engine allows interfacing a system to
  be tested through a variety of means such as a process on a local host
  via a PTY (pseudo terminal), a network host via TELNET, an MVS host via
  3270 protocol, etc. An internal screen image for the system under test
  is constantly maintained, with ability to examine it and to handle
  various events. Input to the system under test can be generated with
  support for functional keys. Ruby test/unit framework is readily
  available for assertions.
       
  Copyright (c) 2003, 2004, Tone Software Corporation
       
  All rights reserved.
       
  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer. 
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution. 
    * Neither the name of the Tone Software Corporation nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission. 
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
  IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
  TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
  PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
  OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  
=end

$:.concat ENV.to_hash['PATH'].to_s.split(':')

require 'tsc/application.rb'
require 'tsc/path.rb'

class Application < TSC::Application

  def initialize
    super('<test case>',
      [ '--mode', 'Operational mode', 'mode', '-m' ],
      [ '--modedir', 'Print out the directory for mode runners', nil, '-M' ],
      [ '--loadpath', 'Print out the loadpath', nil, '-l' ],
      [ '--test', 'Run internal tests', nil, '-t' ],
      [ '--interactive', 'Print out the loadpath', nil, '-i' ],
      [ '--host', 'The host to connect to', "host", '-c' ],
      [ '--user', 'User name', 'user', '-u' ],
      [ '--password', 'User password', 'password', '-p' ],
      [ '--prompt', 'Prompt regexp', 'prompt', '-P' ]
    )
  end

  def start
    handle_errors do
      process_command_line
      $: << File.expand_path(File.join(script_location, '..', 'lib'))

      do_and_exit { run_internal_tests } if @options['test']

      do_and_exit { print_loadpath } if @options['loadpath']
      do_and_exit { print_mode_directory } if @options['modedir']

      require 'tsc/test/accept/runner.rb'
      require 'tsc/test/accept/runtime.rb'

      mode = @options['mode']
      if mode
        runner = File.join Test::Accept::Runner.mode_directory, mode
      else
        runner = ARGV.shift
      end
      unless runner
        do_and_exit { Test::Accept::Runtime.instance.interactive } if @options['interactive']
        raise 'No test runner specified'
      end

      runner_path = figure_runner_path(runner)
      $: << File.dirname(runner_path)

      begin
        Test::Accept::Runner.load(runner_path).new(@options).start
      rescue StandardError, Interrupt, SignalException => exception
        raise TSC::Error.new(File.basename(runner), exception)
      end
    end
    exit! 0
  end

  def figure_runner_path(runner)
    path = [ "#{runner}", "#{runner}.rb" ].map { |_runner|
      Dir[_runner]
    }.flatten.compact.first

    raise "Test runner #{runner.inspect} not found" unless path
    File.expand_path path
  end

  def process_command_line
    @options = super true
  end

  def print_mode_directory
    $stdout.puts Test::Accept::Runner.mode_directory
  end

  def print_loadpath
    $stderr.puts 'Current Ruby load path:'
    $:.each do |_path| 
      $stderr.puts "  #{_path}" 
    end
  end

  def run_internal_tests
    require 'tsc/session/test-suite.rb'
    ARGV.clear
  end

  in_generator_context do |_content|
    _content << '#!' + figure_ruby_path
    _content << TSC::PATH.current.front(File.dirname(figure_ruby_path)).to_ruby_eval
    _content << IO.readlines(__FILE__).slice(1..-1)
  end
end

Application.new.start
